# ruff: noqa: E501 - one text per line reads best
"""English for the server's texts: German original → English, same {placeholders}.

Used by `sprache.tr()`. Film data from TMDB is not in here - it stays German.
"""

EN: dict[str, str] = {
    # --- errors -------------------------------------------------------------
    "Das Bild konnte nicht gelesen werden.": "The picture couldn't be read.",
    "Bitte ein JPG-, PNG-, WebP- oder GIF-Bild.": "Please use a JPG, PNG, WebP or GIF picture.",
    "Das Bild ist zu groß.": "The picture is too large.",
    "Das darf nur der Ersteller oder ein Admin der Gruppe.": "Only the creator or an admin of the group can do that.",
    "Du bist noch in keiner Gruppe – ein Admin nimmt dich auf.": "You're not in a group yet – an admin will take you in.",
    "Das darf nur ein Admin dieser Gruppe.": "Only an admin of this group can do that.",
    "Diese Gruppe gibt es nicht.": "This group doesn't exist.",
    "Der Termin muss in der Zukunft liegen (höchstens ein Jahr).": "The date has to be in the future (at most a year ahead).",
    "Farbe bitte als #rrggbb.": "Please give the colour as #rrggbb.",
    "Erst freigeben, dann zum Admin machen.": "Approve first, then make them admin.",
    "Film nicht gefunden.": "Film not found.",
    "Person nicht gefunden.": "Person not found.",
    "Diese Einladung gilt nicht (mehr). Frag nach einem neuen Link.": "This invitation isn't valid (any more). Ask for a new link.",
    "Keine offene Anfrage.": "No open request.",
    "Nur eigene, freigeschaltete Erfolge können in die Vitrine.": "Only your own unlocked awards can go in the showcase.",
    "Wunsch nicht gefunden.": "Wish not found.",
    "Das darf der Gastgeber des Abends (oder ein Admin der Gruppe).": "Only the host of the night (or an admin of the group) can do that.",
    "Den Stab gibt der Gastgeber weiter (oder ein Admin der Gruppe).": "The host hands on the baton (or an admin of the group).",
    "Den Stab kann nur jemand aus der Gruppe bekommen, der ihn noch nicht hat.": "Only someone in the group who doesn't have it yet can get the baton.",
    "Gerade läuft schon ein Wechsel.": "A handover is already under way.",
    "Du hast den Stab schon.": "You already have the baton.",
    "Die letzte Abstimmung ist gerade erst gescheitert – versuch es in ein paar Minuten noch mal.": "The last vote has only just failed – try again in a few minutes.",
    "Dieser Wechsel ist schon entschieden.": "This handover has already been decided.",
    "Zurückziehen kann nur, wer ihn gestartet hat.": "Only whoever started it can withdraw it.",
    "Annehmen kann nur, wer den Stab bekommen soll.": "Only the person meant to get the baton can accept.",
    "Du kannst hier nicht (mehr) abstimmen.": "You can't vote here (any more).",
    "Du bist nicht in dieser Gruppe.": "You're not in this group.",
    "Bitte zuerst einen Namen wählen.": "Please choose a name first.",
    "Diesen Namen gibt es nicht (oder er ist noch nicht freigegeben).": "This name doesn't exist (or isn't approved yet).",
    "Das darf nur ein Admin.": "Only an admin can do that.",
    "Es gibt noch keinen Termin.": "There's no date yet.",
    "Diesen Kalender gibt es nicht (mehr).": "This calendar doesn't exist (any more).",
    "Senden darf der Gastgeber oder ein Admin der Gruppe (oder OBS mit dem Stream-Key).": "The host or an admin of the group can stream (or OBS with the stream key).",
    "Das Kino ist nicht eingerichtet (MEDIAMTX_WEBRTC_URL fehlt).": "The cinema isn't set up (MEDIAMTX_WEBRTC_URL is missing).",
    "Film nicht im Katalog.": "Film not in the catalogue.",
    "Der Kino-Server ist nicht erreichbar.": "The cinema server can't be reached.",
    "Gerade wird nichts übertragen.": "Nothing is being streamed right now.",
    "Nicht so schnell – kurz durchatmen.": "Not so fast – take a breath.",
    "Leere Nachricht.": "Empty message.",
    "Diese Reaktion gibt es nicht.": "This reaction doesn't exist.",
    "Die Kiste für alle öffnet der Gastgeber des Abends (oder ein Admin der Gruppe).": "The host of the night (or an admin of the group) opens the case for everyone.",
    "Die Kiste wird gerade schon geöffnet.": "The case is already being opened.",
    "Die Kiste ist leer – erst Filme vorschlagen.": "The case is empty – suggest some films first.",
    "Das darf der Gastgeber oder ein Admin der Gruppe.": "Only the host or an admin of the group can do that.",
    "Ein Veto gibt es nur gegen Filme, die gerade vorgeschlagen sind.": "You can only veto films that are currently suggested.",
    "Die KI-Suche ist nicht eingerichtet (LLM_API_KEY fehlt).": "AI search isn't set up (LLM_API_KEY is missing).",
    "TMDB ist nicht eingerichtet (TMDB_API_KEY fehlt).": "TMDB isn't set up (TMDB_API_KEY is missing).",
    "Sync läuft bereits.": "Sync is already running.",
    "Das Bild ist größer als 5 MB.": "The picture is larger than 5 MB.",
    "Kein Bild empfangen.": "No picture received.",
    "Das ist keine Push-Adresse eines bekannten Browsers.": "That's not a push address of a known browser.",
    "Auf keinem Gerät sind Benachrichtigungen eingeschaltet.": "Notifications aren't turned on for any device.",
    "Der Push-Dienst hat die Testnachricht nicht angenommen. Schalte das Gerät aus und wieder ein.": "The push service didn't accept the test message. Turn the device off and on again.",
    "Unbekannter oder kein Bereich gewählt.": "Unknown area, or none chosen.",
    "Diesen Termin gibt es schon in der Umfrage.": "This date is already in the poll.",
    "Diesen Vorschlag gibt es nicht (mehr).": "This proposal doesn't exist (any more).",
    "Den Vorschlag nimmt zurück, wer ihn gemacht hat (oder wer festlegen darf).": "Only whoever made the proposal (or whoever may set the date) can withdraw it.",
    "Die Umfrage beendet, wer sie gestartet hat, der Gastgeber oder ein Admin.": "Whoever started the poll, the host or an admin can end it.",
    "Festlegen darf, wer die Umfrage gestartet hat, der Gastgeber oder ein Admin.": "Whoever started the poll, the host or an admin can set the date.",
    "Es muss mindestens einen Admin geben.": "There has to be at least one admin.",
    "Name fehlt.": "Name missing.",
    "Gerade warten schon viele Anträge – bitte später nochmal.": "Lots of requests are already waiting – please try again later.",
    "Diesen Namen gibt es nicht.": "This name doesn't exist.",
    "Unbekanntes Farbschema oder Schrift.": "Unknown colour theme or font.",
    "Unbekannte Sprache.": "Unknown language.",
    "„{name}“ ist auf diesem Gerät nicht angemeldet – dafür braucht es einen Anmeldecode.": "“{name}” isn't signed in on this device – you need a login code for that.",
    "Dieser Anmeldecode gilt nicht (mehr). Lass dir einen neuen geben.": "This login code isn't valid (any more). Ask for a new one.",
    "Für den ersten Namen braucht es den Einrichtungscode aus dem Server-Log.": "The first name needs the setup code from the server log.",
    "Du hast heute schon {n} KI-Suchen gemacht – morgen geht es weiter.": "You've already made {n} AI searches today – more tomorrow.",
    "Zum Bestätigen deinen Namen genau so eintippen.": "To confirm, type your name exactly as it is.",
    "Wünsche & Ideen sind ausgeschaltet.": "Wishes & ideas are switched off.",
    "Eintrag nicht gefunden.": "Entry not found.",
    "Dieser Kommentar wurde gelöscht.": "This comment was deleted.",
    "Nur Mitglieder der Gruppe können dabei gewesen sein.": "Only members of the group can have been there.",
    "Antwort passt nicht zu diesem Eintrag.": "The reply doesn't belong to this entry.",
    "screenmates gibt es nur mit Einladung.": "screenmates is invitation only.",
    "Zu viele Fehlversuche – bitte in einer Viertelstunde nochmal.": "Too many failed attempts – please try again in a quarter of an hour.",
    "Das darf nur der Ersteller oder ein Admin.": "Only the creator or an admin can do that.",
    # errors with placeholders
    "„{name}“ gibt es schon.": "“{name}” already exists.",
    "Eine Gruppe „{name}“ gibt es schon.": "A group called “{name}” already exists.",
    "Unbekannte Benachrichtigung: {arten}": "Unknown notification: {arten}",
    "Zum Bestätigen „{wort}“ eintippen.": "Type “{wort}” to confirm.",
    "Das sieht nicht nach einem {konto}-Namen aus.": "That doesn't look like a {konto} name.",
    "Mehr als {n} Vorschläge auf einmal werden unübersichtlich.": "More than {n} proposals at once gets confusing.",
    "„{name}“ wartet noch auf die Freigabe durch einen Admin.": "“{name}” is still waiting for an admin to approve it.",
    # --- awards (erfolge.py) ---------------------------------------------------
    "Geheimer Erfolg – wird beim Freischalten enthüllt.": "Secret award – revealed when unlocked.",
    "Terminfinder": "Date finder",
    "Ein Termin aus deiner Umfrage wurde gewählt, und der Abend fand statt": "A date from your poll was chosen, and the night happened",
    "Gesicht zeigen": "Show your face",
    "Ein Profilbild hochgeladen": "Uploaded a profile picture",
    "Zweitgerät": "Second screen",
    "Ein weiteres eigenes Gerät mit einem Anmeldecode verbunden": "Connected another device of your own with a login code",
    "Abo-Profi": "Subscription pro",
    "Die eigenen Streamingdienste eingetragen": "Added your streaming services",
    "Nachteule": "Night owl",
    "Einen Filmabend nach Mitternacht beendet": "Finished a movie night after midnight",
    "Marathon": "Marathon",
    "Drei Filme an einem Tag gemeinsam geschaut": "Watched three films together in one day",
    "Zeitreise": "Time travel",
    "Gemeinsam einen Film von vor 1960 geschaut": "Watched a film from before 1960 together",
    "Genre-Gourmet": "Genre gourmet",
    "Bei Filmabenden Filme aus sechs Genres geschaut": "Watched films from six genres at movie nights",
    "Einstimmig": "Unanimous",
    "Mindestens drei haben einen Film genau gleich bewertet": "At least three people rated a film exactly the same",
    "Jubiläum": "Anniversary",
    "Seit einem Jahr dabei": "Here for a year",
    "Zwischenrufer": "Heckler",
    "Während einer Vorstellung im Kino-Chat mitgeredet": "Chatted in the cinema chat during a show",
    "Bei einem bestätigten Filmabend dabei": "Attended a confirmed movie night",
    "Bei {n} bestätigten Filmabenden dabei": "Attended {n} confirmed movie nights",
    "Erster Abend": "First night",
    "Stammgast": "Regular",
    "Inventar": "Part of the furniture",
    "Teil der Couch": "One with the couch",
    "Einen Termin gesetzt, und der Abend fand statt": "Set a date, and the night happened",
    "{n}× einen Termin gesetzt, und der Abend fand statt": "Set a date {n}×, and the night happened",
    "Gastgeber": "Host",
    "Partyplaner": "Party planner",
    "Hausherr": "Master of the house",
    "Zugesagt und gekommen": "Said yes and showed up",
    "{n}× zugesagt und gekommen": "Said yes and showed up {n}×",
    "Wort gehalten": "Kept your word",
    "Verlässlich": "Reliable",
    "Fels in der Brandung": "Rock solid",
    "Ein eigener Vorschlag wurde gemeinsam geschaut": "One of your suggestions was watched together",
    "{n} eigene Vorschläge wurden gemeinsam geschaut": "{n} of your suggestions were watched together",
    "Volltreffer": "Bullseye",
    "Geschmackssicher": "Sure taste",
    "Trendsetter": "Trendsetter",
    "Einen Film nach einem Filmabend bewertet": "Rated a film after a movie night",
    "{n} Filme nach Filmabenden bewertet": "Rated {n} films after movie nights",
    "Erste Kritik": "First review",
    "Kritiker": "Critic",
    "Feuilleton": "Arts section",
    "Goldene Feder": "Golden quill",
    "Einen Gästebuch-Eintrag zu einem Filmabend geschrieben (ab 20 Zeichen)": "Wrote a guestbook entry for a movie night (20+ characters)",
    "{n} Gästebuch-Einträge zu Filmabenden (ab 20 Zeichen)": "{n} guestbook entries for movie nights (20+ characters)",
    "Erster Eintrag": "First entry",
    "Plaudertasche": "Chatterbox",
    "Chronist": "Chronicler",
    "Ein Herz bekommen": "Received a heart",
    "Herzen von {n} verschiedenen Leuten bekommen": "Received hearts from {n} different people",
    "Gemocht": "Liked",
    "Beliebt": "Popular",
    "Herzensbrecher": "Heartbreaker",
    "Ein Wunsch wurde umgesetzt oder von drei anderen unterstützt": "A wish was built or backed by three others",
    "{n} Wünsche umgesetzt oder von drei anderen unterstützt": "{n} wishes built or backed by three others",
    "Ideengeber": "Idea giver",
    "Visionär": "Visionary",
    "Architekt": "Architect",
    "Eine Vorstellung mit mindestens zwei Zuschauenden gesendet": "Streamed a show with at least two viewers",
    "{n} Vorstellungen mit mindestens zwei Zuschauenden gesendet": "Streamed {n} shows with at least two viewers",
    "Auf Sendung": "On air",
    "Programmkino": "Art-house cinema",
    "Intendanz": "Artistic director",
    "Eine Vorstellung im Kino geschaut": "Watched a show in the cinema",
    "{n} Vorstellungen im Kino geschaut": "Watched {n} shows in the cinema",
    "Erste Reihe": "Front row",
    "Kinogänger": "Cinemagoer",
    "Dauerkarte": "Season ticket",
    "Popcorn-Neuling": "Popcorn rookie",
    "Filmfan": "Film fan",
    "Cineast": "Cinephile",
    "Kritikerliebling": "Critics’ darling",
    "Regielegende": "Directing legend",
    "Hall of Fame": "Hall of Fame",
    "einen geheimen Erfolg": "a secret award",
    "„{name}“": "“{name}”",
    "Film gemeinsam geschaut": "film watched together",
    "Filme gemeinsam geschaut": "films watched together",
    "Person dabei": "person on board",
    "Leute dabei": "people on board",
    "Gruppe": "group",
    "Gruppen": "groups",
    "Herz verteilt": "heart given",
    "Herzen verteilt": "hearts given",
    "Kommentar im Gästebuch": "comment in the guestbook",
    "Kommentare im Gästebuch": "comments in the guestbook",
    "Bewertung abgegeben": "rating given",
    "Bewertungen abgegeben": "ratings given",
    "Film auf Merklisten": "film on watchlists",
    "Filme auf Merklisten": "films on watchlists",
    "Film in den Kisten": "film in the cases",
    "Filme in den Kisten": "films in the cases",
    "Kiste für alle geöffnet": "case opened for everyone",
    "Kisten für alle geöffnet": "cases opened for everyone",
    "Frage an die KI": "question to the AI",
    "Fragen an die KI": "questions to the AI",
    "Erfolg freigeschaltet": "award unlocked",
    "Erfolge freigeschaltet": "awards unlocked",
    "Film im Katalog": "film in the catalogue",
    "Filme im Katalog": "films in the catalogue",
    "Durchschnitt aller Bewertungen": "average of all ratings",
    "Nachricht im Kino-Chat": "message in the cinema chat",
    "Nachrichten im Kino-Chat": "messages in the cinema chat",
    "Reaktion im Kino": "reaction in the cinema",
    "Reaktionen im Kino": "reactions in the cinema",
    "im Kino gestreamt": "streamed in the cinema",
    "Pakete beim Streamen verloren ({quote} %)": "packets lost while streaming ({quote} %)",
    "Horror": "Horror",
    "Gänsehaut garantiert": "Goosebumps guaranteed",
    "Komödie": "Comedy",
    "Zum Lachen": "For a laugh",
    "Thriller": "Thriller",
    "Spannung bis zum Schluss": "Suspense to the end",
    "Action": "Action",
    "Krachen lassen": "Let it rip",
    "Science-Fiction": "Science fiction",
    "Andere Welten": "Other worlds",
    "Drama": "Drama",
    "Großes Gefühlskino": "Big emotions",
    "Animation": "Animation",
    "Nicht nur für Kinder": "Not just for kids",
    "Dokumentarfilm": "Documentary",
    "Wirklich passiert": "Really happened",
    "Neu erschienen": "New releases",
    "Filme der letzten zwei Jahre": "Films from the last two years",
    "Geheimtipps": "Hidden gems",
    "Gut bewertet, aber kaum bekannt": "Well rated, but little known",
    "Klassiker": "Classics",
    "Die besten bis 1989": "The best up to 1989",
    "Aus eurem Katalog": "From your catalogue",
    "Läuft bei uns": "Streams for us",
    "In euren Abos, ohne Aufpreis": "On your subscriptions, no extra cost",
    "Beliebt im Abo": "Popular on the subscription",
    "Kostenlos streamen": "Stream for free",
    "Ohne Abo, meist mit Werbung": "No subscription, usually with ads",
    "Was wo läuft, weiß screenmates nur mit TMDB (TMDB_API_KEY).": "screenmates only knows what streams where with TMDB (TMDB_API_KEY).",
    "Noch niemand hat seine Abos eingetragen (Einstellungen).": "Nobody has added their subscriptions yet (Settings).",
    "Ein Termin wird festgelegt oder verschoben": "A date is set or moved",
    "Jemand schlägt Termine zur Abstimmung vor": "Someone proposes dates for a vote",
    "Die Kiste wird für alle geöffnet": "The case is opened for everyone",
    "Das Kino geht live": "The cinema goes live",
    "Dir wird der Gastgeber-Stab angeboten": "You're offered the host baton",
    "Jemand antwortet auf deinen Kommentar": "Someone replies to your comment",
    "Am Tag danach: den Film vom Vorabend bewerten": "The day after: rate last night's film",
    "🍿 Heute ist Filmabend – {gruppe}": "🍿 Movie night today – {gruppe}",
    "Um {zeit} Uhr{wo} – bist du dabei?": "At {zeit}{wo} – are you in?",
    "⭐ Wie war „{titel}“?": "⭐ How was “{titel}”?",
    "Gib dem Film von gestern deine Sterne – dauert zwei Sekunden.": "Give yesterday's film your stars – takes two seconds.",
    "💬 {name} hat dir geantwortet{film}": "💬 {name} replied to you{film}",
    "🎬 Der Gastgeber-Stab für dich": "🎬 The host baton for you",
    "{name} möchte dir den Stab für den Filmabend geben. Annehmen?": "{name} wants to give you the baton for the movie night. Accept?",
    "📅 Filmabend verschoben – {gruppe}": "📅 Movie night moved – {gruppe}",
    "📅 Filmabend steht – {gruppe}": "📅 Movie night is on – {gruppe}",
    "🗳️ Wann habt ihr Zeit? – {gruppe}": "🗳️ When are you free? – {gruppe}",
    "{name} schlägt {wann} vor. Stimm ab!": "{name} proposes {wann}. Cast your vote!",
    "🎁 Die Kiste geht auf! – {gruppe}": "🎁 The case is opening! – {gruppe}",
    "{name} öffnet die Filmabend-Kiste für alle. Schnell rein!": "{name} is opening the movie-night case for everyone. Hurry in!",
    "🎬 Das Kino ist live – {gruppe}": "🎬 The cinema is live – {gruppe}",
    "{name} sendet „{titel}“. Komm dazu!": "{name} is showing “{titel}”. Join in!",
    "{name} sendet gerade. Komm dazu!": "{name} is streaming right now. Join in!",
    "So sehen Benachrichtigungen aus. Viel Spaß beim nächsten Filmabend!": "This is what notifications look like. Enjoy the next movie night!",
    "Die KI hat keine Filmliste geliefert.": "The AI didn't return a film list.",
    "Die Antwort der KI war kein gültiges JSON.": "The AI's answer wasn't valid JSON.",
    "Die KI ist gerade nicht erreichbar.": "The AI can't be reached right now.",
    "Die Antwort der KI war zu lang und wurde abgeschnitten – anderes Modell wählen (LLM_MODEL).": "The AI's answer was too long and got cut off – choose another model (LLM_MODEL).",
    "Der API-Key der KI wurde abgelehnt.": "The AI's API key was rejected.",
    "Das Guthaben beim KI-Anbieter ist aufgebraucht.": "The credit with the AI provider is used up.",
    "Die KI ist gerade überlastet – bitte gleich noch einmal versuchen.": "The AI is overloaded right now – please try again in a moment.",
    "Die KI antwortete mit Fehler {status}.": "The AI answered with error {status}.",
    "TMDB nicht erreichbar: {fehler}": "TMDB can't be reached: {fehler}",
    "TMDB antwortete mit {status}": "TMDB answered with {status}",
    "Film des Abends: {titel}": "Film of the night: {titel}",
    "Zur Wahl: {filme}": "Up for the vote: {filme}",
    "Dabei: {namen}": "Who's in: {namen}",
    "Bist du dabei? {link}": "Are you in? {link}",
    "Filmabend": "Movie night",
    "Gleich ist Filmabend": "Movie night is about to start",
    "LÖSCHEN": "DELETE",
    "Chronik": "History",
    "Gesehene Filme mit Bewertungen, Teilnehmenden, Gästebuch und Herzen": "Watched films with ratings, participants, guestbook and hearts",
    "Vorschläge, Vetos, Merkliste, Kisten-Öffnungen, Termine, Umfragen, Zusagen, Gastgeber": "Suggestions, vetoes, watchlist, case openings, dates, polls, RSVPs, host",
    "Kino": "Cinema",
    "Chat-Nachrichten und das Programm": "Chat messages and the programme",
    "Wünsche & Ideen": "Wishes & ideas",
    "Alle Wünsche mit Stimmen und Anmerkungen": "All wishes with votes and notes",
    "Erfolge": "Awards",
    "Freigeschaltete Erfolge und ihr Protokoll – was noch da ist, wird neu vergeben": "Unlocked awards and their log – whatever still applies is awarded again",
    "Statistik & KI-Protokoll": "Stats & AI log",
    "Zähler der Seitenleiste (Kino-Traffic, Chat …) und das KI-Nutzungsprotokoll": "Sidebar counters (cinema traffic, chat …) and the AI usage log",
    "Unsere Gruppe": "Our group",
    "Erinnerungen am Tag des Filmabends (vorher und kurz vor Beginn)": "Reminders on the day of the movie night (earlier, and just before it starts)",
    "🎬 Gleich geht’s los – {gruppe}": "🎬 Starting soon – {gruppe}",
    "Der Filmabend beginnt um {zeit} Uhr{wo}. Komm dazu!": "The movie night starts at {zeit}{wo}. Come and join!",
}
